apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress-canary
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "50"   # 50% traffic to green
spec:
  ingressClassName: nginx
  rules:
  - host: "hello.example.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-service-green   # green service
            port:
              number: 80