name: Blue-Green Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      CLUSTER_NAME: gke-tf-bg-cluster
      CLUSTER_REGION: us-central1-a
      USE_GKE_GCLOUD_AUTH_PLUGIN: True

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Authenticate with GCP using service account key
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      # Install gcloud CLI
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install GKE auth plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_REGION --project $PROJECT_ID

      # - name: Build and push Docker image
      #   run: |
      #     gcloud auth configure-docker
      #     docker build -t $IMAGE .
      #     docker push $IMAGE

      - name: Deploy Blue version
        run: |
          kubectl apply -f k8s/deployment-blue.yaml
          kubectl apply -f k8s/service.yaml

      - name: Deploy Green version
        run: |
          kubectl apply -f k8s/deployment-green.yaml

      - name: Deploy service pointing to Blue
        run: |
          kubectl apply -f k8s/service.yaml

      - name: Switch traffic to Green
        run: |
          kubectl patch service hello-service \
            -p '{"spec":{"selector":{"app":"hello","version":"green"}}}'